/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2020-12-13 19:24:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import eduBean.*;
import java.util.regex.*;

public final class insert_005fteach_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/top.jsp", Long.valueOf(1607864167405L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.util.regex");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("eduBean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>기자재 신청</title>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<body>\t\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

	String session_id = (String)session.getAttribute("user");
	String log;

	if (session_id==null) {
		log="<a href=login.jsp>로그인</a>";
	} else {
		log="<a href=logout.jsp>로그아웃</a>";
		Pattern p = Pattern.compile("[A-Z].*");
		Matcher m = p.matcher(session_id);
	}

      out.write("\r\n");
      out.write("<table width=\"75%\" align=\"center\" bgcolor=\"#FFFF99\" border>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\"><b>");
      out.print(log);
      out.write("</b></td>\t\r\n");
      out.write("\t\t<td align=\"center\"><b><a href=\"update_professor.jsp\">교수정보변경</b></td>    \r\n");
      out.write("\t\t<td align=\"center\"><b><a href=\"insert_teach.jsp\">기자재 신청</b></td>\r\n");
      out.write("\t\t<td align=\"center\"><b><a href=\"update_teach.jsp\">기자재 수정</b></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
 
		if (session_id==null) response.sendRedirect("login.jsp"); 
	
      out.write("\r\n");
      out.write("\t\t<table width=\"75%\" align=\"center\" border>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>과목번호</th>\r\n");
      out.write("\t\t\t\t<th>카테고리</th>\r\n");
      out.write("\t\t\t\t<th>기자재 이름</th>\r\n");
      out.write("\t\t\t\t<th>기자재 개수</th>\r\n");
      out.write("\t\t\t</tr><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t");
      eduBean.EquipmentMgr EquipmentMgr = null;
      EquipmentMgr = (eduBean.EquipmentMgr) _jspx_page_context.getAttribute("EquipmentMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (EquipmentMgr == null){
        EquipmentMgr = new eduBean.EquipmentMgr();
        _jspx_page_context.setAttribute("EquipmentMgr", EquipmentMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		Vector vlist = EquipmentMgr.getEquipmentList();		
	
		for(int i=0; i<vlist.size(); i++) {
			Equipment en = (Equipment)vlist.elementAt(i);
	
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\">");
      out.print(en.getCId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">");
      out.print(en.getCName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t");
 if(session_id.equals(en.getMID())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"update_class.jsp?p_id=");
      out.print(en.getMID());
      out.write("&c_id=");
      out.print( en.getCId() );
      out.write("&c_id_no=");
      out.print( en.getCIdNo() );
      out.write('"');
      out.write('>');
}
      out.print(en.getCName());
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">");
      out.print(en.getECount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t");
 if (en.getCName() == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print(en.getCName());
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t");
 if(en.getMID() == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"insert_teach_verify.jsp?c_id=");
      out.print( en.getCId() );
      out.write("&c_id_no=");
      out.print( en.getCIdNo() );
      out.write("&type=1\">신청</a>\r\n");
      out.write("\t\t\t");
 } else if(session_id.equals(en.getMID())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"insert_teach_verify.jsp?c_id=");
      out.print( en.getCId() );
      out.write("&c_id_no=");
      out.print( en.getCIdNo() );
      out.write("&type=2\">취소</a>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table> \r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
