/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2020-12-10 02:01:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import eduBean.*;

public final class update_005fscore_005fverify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("eduBean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>성적등록</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!--【5-③】-->\r\n");
      out.write("\t\t");
      eduBean.GradeMgr gradeMgr = null;
      gradeMgr = (eduBean.GradeMgr) _jspx_page_context.getAttribute("gradeMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (gradeMgr == null){
        gradeMgr = new eduBean.GradeMgr();
        _jspx_page_context.setAttribute("gradeMgr", gradeMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar message = \"\";\r\n");
      out.write("\t\t");

			String sMessage;
			
			request.setCharacterEncoding("utf-8");
			int year = Integer.parseInt(request.getParameter("year"));
			int semester = Integer.parseInt(request.getParameter("semester"));						
			String result = null;
			String cid[] = request.getParameterValues("cid");			
			String cidnos[] = request.getParameterValues("cidno");
			int [] cidno = new int [cidnos.length];
			for(int i = 0; i < cidnos.length; i++) { cidno[i] = Integer.parseInt(cidnos[i]); }
			String cname[] = request.getParameterValues("cname");
			String sid[] = request.getParameterValues("sid");
			String sname[] = request.getParameterValues("sname");
			String scores[] = request.getParameterValues("score");
			String scounter = request.getParameter("counter");
			int counter = Integer.parseInt(scounter);			
			String dburl = "jdbc:oracle:thin:@210.94.199.20:1521:dblab";
			String user = "FE2018112028";	// 본인 아이디(ex.ST0000000000)
			String passwd = "FE2018112028";	// 본인 패스워드(ex.ST0000000000)
			String dbdriver = "oracle.jdbc.driver.OracleDriver";
			
			Connection myConn = null;     
			CallableStatement cstmt = null;
			
			try {
				//【5-④】
				Class.forName(dbdriver);
            	myConn = DriverManager.getConnection(dburl, user, passwd);
				for(int i = 0; i < counter; i++){
					result = gradeMgr.setScore(scores[i], sid[i], cid[i], cidno[i], year, semester);
				
	              		if (result.equals("20002")){
	        				result = "등록 불가(사유 : 현재 학기 성적만 입력 가능합니다.)";
	     		
      out.write("\r\n");
      out.write("\t            \t\t\tmessage = message + \"");
      out.print(result);
      out.write("\" + \"\\n\"\r\n");
      out.write("            \t\t");

	                			break;
				} else if(result.equals("20003")){
   	     				result = "등록 불가(사유 : 학기 중에만 성적 입력 가능합니다.)";
			
      out.write("\r\n");
      out.write("\t\t\t\t\tmessage = message + \"");
      out.print(result);
      out.write("\" + \"\\n\"\r\n");
      out.write("\t\t\t");

					break;
				} else {
					result = cname[i] + "-" + sname[i] + "-" + result;
			
      out.write("\r\n");
      out.write("\t\t\t\t\tmessage = message + \"");
      out.print(result);
      out.write("\" + \"\\n\"\r\n");
      out.write("\t\t\t");

				}
			      }
			} catch(SQLException ex) {
				System.err.println("SQLException: " + ex.getMessage());
			} 	
		
      out.write("\t\t\r\n");
      out.write("\t\t\talert(message);\r\n");
      out.write("\t\t\tlocation.href = \"grade.jsp?year=");
      out.print(year);
      out.write("&semester=");
      out.print(semester);
      out.write("\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
